source :rubygems
#gem 'ruby-debug19', :require => 'ruby-debug'
gem 'debugger', :group => [:development, :test]
gem 'puzzle_reader'

group :development do
  gem 'pry'
  gem 'guard-rspec'
  gem 'guard-cucumber'
end
group :test do
  gem 'cucumber'
  gem 'rspec'
end
